### ISSUE TITLE
Getting ECONNREFUSED for automatic mongo db connection

### ISSUE THREAD

**Issue by gra-m** [gra-m/gd-pet-clinic#25]

**Comment by gra-m** [comment]
C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r> npm start

> loc8r@0.0.0 start
> node ./bin/www

Mongoose disconnected
Mongoose connection error: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\connection.js:807:32)
    at C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\index.js:342:10
    at C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\index.js:1176:10)
    at Mongoose.connect (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\index.js:341:20)
    at Object.<anonymous> (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\app_server\models\db.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
    stale: false,
    at NativeConnection.Connection.openUri (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\connection.js:807:32)
    at C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\index.js:342:10
    at C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\index.js:1176:10)
    at Mongoose.connect (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\node_modules\mongoose\lib\index.js:341:20)
    at Object.<anonymous> (C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r\app_server\models\db.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
This is cool connect ECONNREFUSED 127.0.0.1:27017

**Comment by gra-m** [comment]
Plain run does not open either (though it did earlier today) --> just realised what it is, auto close not working so I did:
db.shutdownServer() what I should of done was: [](https://docs.mongodb.com/mongodb-shell/connect/#disconnect-from-a-deployment)Disconnect from a Deployment
To disconnect from a deployment and exit mongosh, you can:

Type .exit, exit, or exit().
Type quit or quit().
Press Ctrl + D.
Press Ctrl + C twice.
PS C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r> mongosh
Current Mongosh Log ID: 623acc9d62cd97f562dea259
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.2.2
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
PS C:\Users\Gra_m\Documents\WEB\Heroku\MEAN\Loc8r>

**Comment by gra-m** [comment]
Self caused bug, I closed down server in error ReadMe updated.
